"""empty message

Revision ID: 067629a62d97
Revises: 9fbb34510550
Create Date: 2023-07-10 12:23:36.530611

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '067629a62d97'
down_revision = '9fbb34510550'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_views',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'question_id')
    )
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('times_viewed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('times_viewed', mysql.BIGINT(), autoincrement=False, nullable=True))

    op.drop_table('question_views')
    # ### end Alembic commands ###
